// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWAD_L4.DAL;

#nullable disable

namespace SWAD_L4.DAL.Migrations
{
    [DbContext(typeof(LeisureDbContext))]
    partial class LeisureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWAD_L4.Core.Entities.AttractionEntity", b =>
                {
                    b.Property<int>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttractionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttractionId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            AttractionId = 1,
                            Name = "Батут",
                            Price = 150m
                        },
                        new
                        {
                            AttractionId = 2,
                            Name = "Лабіринт",
                            Price = 200m
                        },
                        new
                        {
                            AttractionId = 3,
                            Name = "Колесо огляду",
                            Price = 250m
                        },
                        new
                        {
                            AttractionId = 4,
                            Name = "Гойдалки",
                            Price = 100m
                        },
                        new
                        {
                            AttractionId = 5,
                            Name = "Зимова карусель",
                            Price = 180m
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("CostumeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CostumeName = "Міккі Маус",
                            Price = 300m
                        },
                        new
                        {
                            CharacterId = 2,
                            CostumeName = "Поні Іскорка",
                            Price = 350m
                        },
                        new
                        {
                            CharacterId = 3,
                            CostumeName = "Соня з Ведмедиком",
                            Price = 250m
                        },
                        new
                        {
                            CharacterId = 4,
                            CostumeName = "Кіт Матроскін",
                            Price = 270m
                        },
                        new
                        {
                            CharacterId = 5,
                            CostumeName = "Снігуронька",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderAttractionEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("AttractionId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "AttractionId");

                    b.HasIndex("AttractionId");

                    b.ToTable("OrderAttractions");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AttractionId = 1
                        },
                        new
                        {
                            OrderId = 1,
                            AttractionId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            AttractionId = 3
                        },
                        new
                        {
                            OrderId = 3,
                            AttractionId = 4
                        },
                        new
                        {
                            OrderId = 3,
                            AttractionId = 5
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderCharacterEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("OrderCharacters");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CharacterId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CharacterId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            CharacterId = 3
                        },
                        new
                        {
                            OrderId = 4,
                            CharacterId = 4
                        },
                        new
                        {
                            OrderId = 5,
                            CharacterId = 5
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramType")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            CustomerName = "Олена",
                            CustomerPhone = "0987654821",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramType = 0
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            CustomerName = "Іван",
                            CustomerPhone = "1234567860",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramType = 1
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            CustomerName = "Марія",
                            CustomerPhone = "0987654341",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramType = 0
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 4,
                            CustomerName = "Андрій",
                            CustomerPhone = "1234567890",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramType = 1
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 5,
                            CustomerName = "Наталя",
                            CustomerPhone = "0987654321",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProgramType = 1
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderZoneEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ZoneId");

                    b.HasIndex("ZoneId");

                    b.ToTable("OrderZones");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ZoneId = 1
                        },
                        new
                        {
                            OrderId = 1,
                            ZoneId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            ZoneId = 3
                        },
                        new
                        {
                            OrderId = 2,
                            ZoneId = 4
                        },
                        new
                        {
                            OrderId = 3,
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.ZoneEntity", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ZoneId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            Name = "Ігрова зона",
                            Price = 200m
                        },
                        new
                        {
                            ZoneId = 2,
                            Name = "Спортивна зона",
                            Price = 150m
                        },
                        new
                        {
                            ZoneId = 3,
                            Name = "Зона релаксу",
                            Price = 175m
                        },
                        new
                        {
                            ZoneId = 4,
                            Name = "Квест-зона",
                            Price = 300m
                        },
                        new
                        {
                            ZoneId = 5,
                            Name = "Тематична зона",
                            Price = 290m
                        });
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderAttractionEntity", b =>
                {
                    b.HasOne("SWAD_L4.Core.Entities.AttractionEntity", "Attraction")
                        .WithMany("OrderAttractions")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAD_L4.Core.Entities.OrderEntity", "Order")
                        .WithMany("Attractions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderCharacterEntity", b =>
                {
                    b.HasOne("SWAD_L4.Core.Entities.CharacterEntity", "Character")
                        .WithMany("OrderCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAD_L4.Core.Entities.OrderEntity", "Order")
                        .WithMany("Characters")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderEntity", b =>
                {
                    b.HasOne("SWAD_L4.Core.Entities.CustomerEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderZoneEntity", b =>
                {
                    b.HasOne("SWAD_L4.Core.Entities.OrderEntity", "Order")
                        .WithMany("Zones")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAD_L4.Core.Entities.ZoneEntity", "Zone")
                        .WithMany("OrderZones")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.AttractionEntity", b =>
                {
                    b.Navigation("OrderAttractions");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.CharacterEntity", b =>
                {
                    b.Navigation("OrderCharacters");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.OrderEntity", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("Characters");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SWAD_L4.Core.Entities.ZoneEntity", b =>
                {
                    b.Navigation("OrderZones");
                });
#pragma warning restore 612, 618
        }
    }
}
